//các phần import: 

import java.awt.Color;
import java.sql.Connection;
import java.sql.JDBCType;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sun.security.x509.RDN;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MyPC
 */
//khai báo class: 
public class Sach extends javax.swing.JFrame {

    KetNoiQLTV ketNoiQLTV = null;
    Connection connection = null;

    /**
     * Creates new form Sach
     */
    //phương thức Sach: 
    public Sach() {
        ketNoiQLTV = new KetNoiQLTV();
        connection = ketNoiQLTV.getJDBCConnection();
        initComponents();
        this.setLocationRelativeTo(null);
        //gọi hàm loadData trong phương thức Sach: 
        loadData();
        //timKiem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        masachchon = new javax.swing.JRadioButton();
        tensachchon = new javax.swing.JRadioButton();
        nhaxuatbanchon = new javax.swing.JRadioButton();
        namxuatbanchon = new javax.swing.JRadioButton();
        theloaichon = new javax.swing.JRadioButton();
        tacgiachon = new javax.swing.JRadioButton();
        timkiem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        masachtt = new javax.swing.JTextField();
        tensachtt = new javax.swing.JTextField();
        nhaxuabantt = new javax.swing.JTextField();
        namxuatbantt = new javax.swing.JTextField();
        theloaitt = new javax.swing.JTextField();
        giatientt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        soluongtt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tacgiatt = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangsach = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HÀN TRUNG KIÊN 20162220");

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-back-icon.png"))); // NOI18N
        jButton5.setText("Quay lại ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        masachchon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(masachchon);
        masachchon.setText("Mã sách: ");
        masachchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masachchonActionPerformed(evt);
            }
        });

        tensachchon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(tensachchon);
        tensachchon.setText("Tên sách: ");

        nhaxuatbanchon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(nhaxuatbanchon);
        nhaxuatbanchon.setText("Nhà xuất bản: ");

        namxuatbanchon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(namxuatbanchon);
        namxuatbanchon.setText("Năm xuất bản: ");

        theloaichon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(theloaichon);
        theloaichon.setText("Thể loại: ");

        tacgiachon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(tacgiachon);
        tacgiachon.setText("Tác giả: ");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TÌM KIẾM SÁCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-icon.png"))); // NOI18N
        jButton1.setText("Tìm kiếm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tacgiachon)
                            .addComponent(namxuatbanchon)
                            .addComponent(masachchon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tensachchon)
                                    .addComponent(theloaichon))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nhaxuatbanchon)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masachchon)
                    .addComponent(tensachchon))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namxuatbanchon)
                    .addComponent(theloaichon))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tacgiachon)
                    .addComponent(nhaxuatbanchon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NHẬP THÔNG TIN SÁCH");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(163, 163, 163))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insert-image-icon (1).png"))); // NOI18N
        jButton2.setText("Thêm ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-document-edit-icon.png"))); // NOI18N
        jButton3.setText("Sửa ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Error-icon.png"))); // NOI18N
        jButton4.setText("Xóa ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã sách: ");

        jLabel4.setText("Tên sách: ");

        jLabel5.setText("Nhà xuất bản :");

        jLabel6.setText("Năm xuất bản: ");

        jLabel7.setText("Thể loại: ");

        jLabel8.setText("Giá tiền: ");

        jLabel9.setText("Số lượng: ");

        jLabel11.setText("Tác giả: ");

        jButton11.setBackground(new java.awt.Color(102, 102, 102));
        jButton11.setText("Reset");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namxuatbantt)
                    .addComponent(masachtt)
                    .addComponent(tensachtt)
                    .addComponent(nhaxuabantt)
                    .addComponent(theloaitt)
                    .addComponent(giatientt)
                    .addComponent(soluongtt)
                    .addComponent(tacgiatt))
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jButton11)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masachtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tensachtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhaxuabantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namxuatbantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theloaitt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giatientt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(soluongtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tacgiatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton11))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("HIỂN THỊ SÁCH");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(339, 339, 339))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bangsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bangsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangsach);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programming-Show-Property-icon.png"))); // NOI18N
        jButton7.setText("Hiển thị toàn bộ sách");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setText("Thêm vào 1 file ");

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setText("Xuất ra 1 file ");

        jButton10.setBackground(new java.awt.Color(102, 102, 102));
        jButton10.setText("Thống kê ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Đăng xuẩt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(229, 229, 229)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(280, 280, 280)
                .addComponent(jButton6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            suaDuLieu();
        } catch (SQLException ex) {
            Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
        JOptionPane.showMessageDialog(this,"Sửa thông tin sách thành công!");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int chose = JOptionPane.showConfirmDialog(null, "Xác nhận", "Thêm", 0);
        if (chose == 0) {
            try {
                xoaSach();
            } catch (SQLException ex) {
                Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadData();
                JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            themSach();
        } catch (SQLException ex) {
            Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
        JOptionPane.showMessageDialog(this, "Thêm sách thành công!");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new TrangChu().setVisible(true);
                this.dispose();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // timKiem();
        if (masachchon.isSelected()) {
            timKiem();
        } else if (tensachchon.isSelected()) {
            timKiemTheoTen();
        } else if (namxuatbanchon.isSelected()) {
            timKiemTheoNamXuatBan();
        } else if (theloaichon.isSelected()) {
            timKiemTheoTheLoai();
        } else if (tacgiachon.isSelected()) {
            timKiemTheoTacGia();
        } else if (nhaxuatbanchon.isSelected()) {
            timKiemTheoNhaXuatBan();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void masachchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masachchonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_masachchonActionPerformed

    private void bangsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangsachMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_bangsachMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        masachtt.setText("");
        tensachtt.setText("");
        theloaitt.setText("");
        namxuatbantt.setText("");
        nhaxuabantt.setText("");
        tacgiatt.setText("");
        giatientt.setText("");
        soluongtt.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new ThongKeSach().setVisible(true);
                this.dispose();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int chose = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đăng xuất không?", "Xác nhận", 0);
        if (chose == 0) {
            
               new Menu().setVisible(true );
        this.dispose();
            
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     *
     * @param args the command line arguments
     */
    //hàm Main(): 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sach sach = new Sach();

                sach.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangsach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField giatientt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton masachchon;
    private javax.swing.JTextField masachtt;
    private javax.swing.JRadioButton namxuatbanchon;
    private javax.swing.JTextField namxuatbantt;
    private javax.swing.JTextField nhaxuabantt;
    private javax.swing.JRadioButton nhaxuatbanchon;
    private javax.swing.JTextField soluongtt;
    private javax.swing.JRadioButton tacgiachon;
    private javax.swing.JTextField tacgiatt;
    private javax.swing.JRadioButton tensachchon;
    private javax.swing.JTextField tensachtt;
    private javax.swing.JRadioButton theloaichon;
    private javax.swing.JTextField theloaitt;
    private javax.swing.JTextField timkiem;
    // End of variables declaration//GEN-END:variables
       //hàm loadData() :

    private void loadData() {
        bangsach.removeAll();
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach";
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);
         bangsach.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
          
            public void valueChanged(ListSelectionEvent e) {
                if (bangsach.getSelectedRow() >= 0) {
                    masachtt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 0).toString());
                    tensachtt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 1).toString());
                    theloaitt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 2).toString());
                    namxuatbantt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 3).toString());
                    nhaxuabantt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 4).toString());
                    tacgiatt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 5).toString());
                    giatientt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 6).toString());
                    soluongtt.setText(bangsach.getValueAt(bangsach.getSelectedRow(), 7).toString());

                }
            }

        });
    }

    //hàm tìm kiếm theo 
    private void timKiem() {
        bangsach.removeAll();
        String s;
        s = timkiem.getText();
        int idNhapVao;
        idNhapVao = Integer.parseInt(s);
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach where idSach=" + idNhapVao;
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);

    }

    //tìm kiếm theo tên : 
    private void timKiemTheoTen() {
        bangsach.removeAll();
        String tenSachNhapVao = timkiem.getText();
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach where tenSach = '" + tenSachNhapVao + "'";
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);

    }

    //ham them sach: 

    private void themSach() throws SQLException {
        //doc id
        String sId = "";
        sId = masachtt.getText();
        int idSach = Integer.parseInt(sId);

        //doc ten 
        String tenSach = "";
        tenSach = tensachtt.getText();
        //doc the loai 
        String theLoaiSach = "";
        theLoaiSach = theloaitt.getText();
        //doc nam xuat ban 
        String namXuatBanSach = "";
        namXuatBanSach = namxuatbantt.getText();
        //doc nha xuat ban 
        String nhaXuatBanSach = "";
        nhaXuatBanSach = nhaxuabantt.getText();
        //doc ten tac gia 
        String tenTacGia = "";
        tenTacGia = tacgiatt.getText();

        //doc gia tien 
        String sgiaTien = new String();
        sgiaTien = giatientt.getText();
        Double giaTien;
        giaTien = Double.parseDouble(sgiaTien);
        //doc so luong 
        String ssoluong = soluongtt.getText();
        int soLuong = Integer.parseInt(ssoluong);

        String sql1 = "insert into quan_ly_thu_vien.sach (idSach, tenSach, theLoaiSach, namXuatBanSach, nhaXuatBanSach, tenTacGia, giaTien, soLuong) values ('" + idSach + "','" + tenSach + "', '" + theLoaiSach + "', '" + namXuatBanSach + "', '" + nhaXuatBanSach + "', '" + tenTacGia + "',' " + giaTien + "', '" + soLuong + "');";
        Statement statement = null;
        ResultSet resultSet = null;
//        try {
//            statement = connection.createStatement();
//            resultSet = statement.executeQuery(sql1);
//            
//            
//        } catch (Exception e) {
//            e.printStackTrace();
//
//        }
        statement = connection.createStatement();
        statement.executeUpdate(sql1);

    }

    //ham tim kiem theo nam xuat ban

    private void timKiemTheoNamXuatBan() {
        bangsach.removeAll();
        String namXuatBanNhapVao = timkiem.getText();
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach where namXuatBanSach = '" + namXuatBanNhapVao + "'";
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);

    }

    //tim kiem theo the loai 

    private void timKiemTheoTheLoai() {
        bangsach.removeAll();
        String theLoaiNhapVao = timkiem.getText();
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach where theLoaiSach = '" + theLoaiNhapVao + "'";
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);

    }

    //tim kiem theo tac gia

    private void timKiemTheoTacGia() {
        bangsach.removeAll();
        String tacGiaNhapVao = timkiem.getText();
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach where tenTacGia = '" + tacGiaNhapVao + "'";
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);

        

    }

    //tim kiem theo nha san xuat

    private void timKiemTheoNhaXuatBan() {
        bangsach.removeAll();
        String nhaXuatBanNhapVao = timkiem.getText();
        String[] columns = {"Mã", "Tên", "Thể Loại", "Năm XB", "Nhà XB", "Tác giả", "Giá tiền", "Số lượng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "select * from sach where nhaXuatBanSach = '" + nhaXuatBanNhapVao + "'";
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("idSach"));
                vector.add(resultSet.getString("tenSach"));
                vector.add(resultSet.getString("theLoaiSach"));
                vector.add(resultSet.getString("namXuatBanSach"));
                vector.add(resultSet.getString("nhaXuatBanSach"));
                vector.add(resultSet.getString("tenTacGia"));
                vector.add(resultSet.getDouble("giaTien"));
                vector.add(resultSet.getInt("soLuong"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangsach.setModel(model);


    }

    //ham xoa sach 

    private void xoaSach() throws SQLException {
        String sId = "";
        sId = masachtt.getText();
        int idSach = Integer.parseInt(sId);

//        //doc ten 
//        String tenSach = "";
//        tenSach = tensachtt.getText();
//        //doc the loai 
//        String theLoaiSach = "";
//        theLoaiSach = theloaitt.getText();
//        //doc nam xuat ban 
//        String namXuatBanSach = "";
//        namXuatBanSach = namxuatbantt.getText();
//        //doc nha xuat ban 
//        String nhaXuatBanSach = "";
//        nhaXuatBanSach = nhaxuabantt.getText();
//        //doc ten tac gia 
//        String tenTacGia = "";
//        tenTacGia = tacgiatt.getText();
//
//        //doc gia tien 
//        String sgiaTien = new String();
//        sgiaTien = giatientt.getText();
//        Double giaTien;
//        giaTien = Double.parseDouble(sgiaTien);
//        //doc so luong 
//        String ssoluong = soluongtt.getText();
//        int soLuong = Integer.parseInt(ssoluong);

        String sql1 = "delete from quan_ly_thu_vien.sach where idSach = "+idSach;
        Statement statement = null;
        ResultSet resultSet = null;
//        try {
//            statement = connection.createStatement();
//            resultSet = statement.executeQuery(sql1);
//            
//            
//        } catch (Exception e) {
//            e.printStackTrace();
//
//        }
        statement = connection.createStatement();
        statement.executeUpdate(sql1);

    }
    //ham click vao table: 
    
    
    //ham sua du lieu 
    private void suaDuLieu() throws SQLException{
        //doc id
        String sId = "";
        sId = masachtt.getText();
        int idSach = Integer.parseInt(sId);

        //doc ten 
        String tenSach = "";
        tenSach = tensachtt.getText();
        //doc the loai 
        String theLoaiSach = "";
        theLoaiSach = theloaitt.getText();
        //doc nam xuat ban 
        String namXuatBanSach = "";
        namXuatBanSach = namxuatbantt.getText();
        //doc nha xuat ban 
        String nhaXuatBanSach = "";
        nhaXuatBanSach = nhaxuabantt.getText();
        //doc ten tac gia 
        String tenTacGia = "";
        tenTacGia = tacgiatt.getText();

        //doc gia tien 
        String sgiaTien = new String();
        sgiaTien = giatientt.getText();
        Double giaTien;
        giaTien = Double.parseDouble(sgiaTien);
        //doc so luong 
        String ssoluong = soluongtt.getText();
        int soLuong = Integer.parseInt(ssoluong);
        String sql1 = "update  sach set   tenSach='"+tenSach+"', theLoaiSach='"+theLoaiSach+"',namXuatBanSach='"+namXuatBanSach+"',nhaXuatBanSach='"+  nhaXuatBanSach+"',tenTacGia='"+ tenTacGia+"',giaTien='"+giaTien+"',soLuong='"+ soLuong +"'  where idSach='"+idSach+"';";
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql1);

        
    }
}
